version: "3.7"
services:
  betteraiapp:
    container_name: public
    build:
      context: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3020:5173"
    env_file:
      - ./.env
